### PR TITLE
improved trapping_rain_water idea

### PR DESCRIPTION
**Pull request by hemanthkotaprolu**
### Issue #185

Improved algorithm from O(n<sup>2</sup>) --> O(n). Please review and let me know.
Thanks

### CODE REVIEW

**Review by jeremie1112 — CHANGES_REQUESTED** [review]
Hello, it's a very good way to improve this program.
Can you make another program including your changes please ?
And name it Trapping_Rain_Water_Improved.cpp

**Comment by hemanthkotaprolu** [comment]
Yeah will do that.
Thanks

**Comment by jeremie1112** [comment]
> Yeah will do that. Thanks

@hemanthkotaprolu counting on you

**Comment by hemanthkotaprolu** [comment]
Please review and let me know.

**Review by jeremie1112 — APPROVED** [review]
Good PR and fast response.
Thanks

**Pull request merged**
