### PR TITLE
Added Bubble sort in c

### PR DESCRIPTION
**Pull request by tovinayak**

### CODE REVIEW

**Comment by tovinayak** [comment]
would you please tag this pr with 'hacktoberfest-accepted' 
please

**Review by jeremie1112 — CHANGES_REQUESTED** [review]
please put the file in 'All_Programs_and_algorithms/Algorithms/bubblesort/C/'

**Comment by jeremie1112** [comment]
@tovinayak Also since the Bubblesort program is already done, i will accept it if you do the requested change.

**Comment by tovinayak** [comment]
I'll put the program at the mentioned location

**Review by jeremie1112 — APPROVED** [review]

**Comment by tovinayak** [comment]
Thank you

**Pull request merged**
