### PR TITLE
Added insertion sort in C++

### PR DESCRIPTION
**Pull request by Esha-Sherring**
Added insertion sort in C++ #1

### CODE REVIEW

**Review by jeremie1112 — CHANGES_REQUESTED** [review]
@Esha-Sherring Hey can you put the Insertion sort.cpp in the C++ folder instead as there is already one C++folder. You only to edit that so that I can merge it

**Comment by Esha-Sherring** [comment]
> @Esha-Sherring Hey can you put the Insertion sort.cpp in the C++ folder instead as there is already one C++folder. You only to edit that so that I can merge it

yes ! on it

**Comment by jeremie1112** [comment]
@Esha-Sherring There is already the file for insertion sort, you can put another insertion sort with your name as such "Esha-Insertion_sort.cpp"

**Comment by Esha-Sherring** [comment]
> @Esha-Sherring There is already the file for insertion sort, you can put another insertion sort with your name as such "Esha-Insertion_sort.cpp"

ok
but there is no C++ folder in it so should I make one?

**Comment by Esha-Sherring** [comment]
> @Esha-Sherring There is already the file for insertion sort, you can put another insertion sort with your name as such "Esha-Insertion_sort.cpp"

I have done the same please check .
Apologies for any inconvenience as I am new to this.

**Comment by jeremie1112** [comment]
@Esha-Sherring I have merged your insertion code now make a new PR for the selection sort in java. Thank you

**Comment by Esha-Sherring** [comment]
> @Esha-Sherring I have merged your insertion code now make a new PR for the selection sort in java. Thank you

Okay doing it now!

**Comment by Esha-Sherring** [comment]
> @Esha-Sherring I have merged your insertion code now make a new PR for the selection sort in java. Thank you

Done !.

**Comment by Esha-Sherring** [comment]
I have send the PR for selection sort but it shows that the issue is closed .As I am new to this I am not very clear about it.

**Comment by jeremie1112** [comment]
@Esha-Sherring Nice job, you did well. I am closing this PR since i merged the other ones

**Comment by Esha-Sherring** [comment]
> @Esha-Sherring Nice job, you did well. I am closing this PR since i merged the other ones

Thank You

**Comment by Esha-Sherring** [comment]
On my hacktober profile it show........will it be aprroved?
Please guide because I am new
Capture

**Comment by jeremie1112** [comment]
@Esha-Sherring Yes it will be approved since you sent a PR and thanks for contributing in my repo

**Pull request closed without merging**
