### PR TITLE
Selection sort problem solution in java

### PR DESCRIPTION
**Pull request by s4shantanu**
Hey,
Actually, I'm asking to you assign the task but after I read the contribution file then I directly push this repo.
Please approve my pr I have also a pr to push if you approve this I will push all the pr.

### CODE REVIEW

**Review by s4shantanu — COMMENTED** [review]
Code is working Properly

**Review by jeremie1112 — CHANGES_REQUESTED** [review]
Hello, this is a good program but can you move it to : Algorithms/Selection_sort/Java/Selectionsorting.java

Please ?

**Comment by s4shantanu** [comment]
> Hello, this is a good program but can you move it to : Algorithms/Selection_sort/Java/Selectionsorting.java
> 
> Please ?

Sure @jeremie1112

**Comment by s4shantanu** [comment]
Changes Done.
Please Approve my PR @jeremie1112

**Review by s4shantanu — COMMENTED** [review]
The path is updated.
Approve the PR and merged it

**Comment by s4shantanu** [comment]
Changes Done Daniel.

**Comment by jeremie1112** [comment]
Hello, sorry wasn't at home today.

**Review by jeremie1112 — CHANGES_REQUESTED** [review]
Hello, you have to move it in another folder. 
The file is in "Algorithms/Selection-sort/Selectionsorting .java"
You have to move it in "Algorithms/Selection_sort/Java/Selectionsorting.java"
If there is not a Java folder, you can create it

**Comment by jeremie1112** [comment]
Don't worry, i'll accept your PR after the changes.

**Comment by s4shantanu** [comment]
Ok

> Hello, you have to move it in another folder. The file is in "Algorithms/Selection-sort/Selectionsorting .java" You have to move it in "Algorithms/Selection_sort/Java/Selectionsorting.java" If there is not a Java folder, you can create it

Okay fine

**Comment by s4shantanu** [comment]
Now you can check @jeremie1112 I add 2 files insertion sorting and selection sorting with the right path and right code.

**Review by s4shantanu — COMMENTED** [review]
I add 2 sorting method files with correct path

**Comment by jeremie1112** [comment]
Hello, thank you for the effort, it's good now brother

**Comment by s4shantanu** [comment]
Please Approve the PR

**Comment by jeremie1112** [comment]
Hello, if you are talking about hacktoberfest, I added the tag **hacktoberfest-accepted** so it's okay you will be accepted

**Comment by s4shantanu** [comment]
Okay, Thanks @jeremie1112

**Pull request merged**
