### PR TITLE
Added Map data structure in Python

### PR DESCRIPTION
**Pull request by Asnegha**

### CODE REVIEW

**Review by jeremie1112 — COMMENTED** [review]
Hello, do you also have the driver program (main) ?

**Comment by Asnegha** [comment]
Hi, I just forked and made changes.

**Comment by jeremie1112** [comment]
Hello, I don't see the changes. Can you verify if you did a PR ?

**Comment by Asnegha** [comment]
Hi, I added the file inside a folder and I am able to see the changes. Shall I close and raise the request again?

**Comment by jeremie1112** [comment]
You can try to git add, commit and push the PR again ?
Else, you can do another PR if you want.

**Pull request closed without merging**
