### PR TITLE
QuickSort Implementation in Java

### PR DESCRIPTION
**Pull request by AnjalBam**
It is the short implementation of Quicksort algorithm in java.

### CODE REVIEW

**Comment by AnjalBam** [comment]
@jeremie1112 was there any mistake so you just closed this pull request without merging...

**Comment by jeremie1112** [comment]
@AnjalBam Yes sorry i was writing where you should put the algorithms. 

Please put the quicksort.java in Algorithms/quicksort/java

**Comment by AnjalBam** [comment]
@jeremie1112 I fixed the issue I hope it is fine now.

**Review by jeremie1112 — CHANGES_REQUESTED** [review]
@AnjalBam Sorry to ask you for further changes but you've put the quicksort.java file inside the binary_search folder. You can put it in the quicksort folder, please. You can do it bro <3

**Comment by AnjalBam** [comment]
Oh sorry bro my bad.

**Comment by AnjalBam** [comment]
> @AnjalBam Sorry to ask you for further changes but you've put the quicksort.java file inside the binary_search folder. You can put it in the quicksort folder, please. You can do it bro <3

I hope it is fixed now brother...

**Review by jeremie1112 — APPROVED** [review]
nice job 👍

**Pull request merged**
