### PR TITLE
Create Implementation of Polynomial using Linked List

### PR DESCRIPTION
**Pull request by moh003-suh**
Program for Implementation of polynomials using Linked List

### CODE REVIEW

**Review by jeremie1112 — CHANGES_REQUESTED** [review]
Please put it in the "Data_structures/LinkedList/c/Implementation of Polynomial using Linked List" folder. you forgot about the language c folder

**Comment by moh003-suh** [comment]
> Please put it in the "Data_structures/LinkedList/c/Implementation of Polynomial using Linked List" folder. you forgot about the language c folder

okay I'll do soo

**Comment by moh003-suh** [comment]
> Please put it in the "Data_structures/LinkedList/c/Implementation of Polynomial using Linked List" folder. you forgot about the language c folder

Done

**Comment by jeremie1112** [comment]
@moh003-suh closing this since i already merge the other one

**Pull request closed without merging**
