### PR TITLE
Added DS Sorting methods

### PR DESCRIPTION
**Pull request by PritKalariya**
Added bubble sort, selection sort, insertion sort, merge sort and quick sort programs.

### CODE REVIEW

**Review by jeremie1112 — CHANGES_REQUESTED** [review]
@PritKalariya Hey can you put the cpp file in the corresponding file as such Data_structures/Bubble_sort/C++/Bubble_Sort.cpp. Thank you

**Comment by PritKalariya** [comment]
OK! Sure! How should i do that ? Should I make another PR ?

**Comment by jeremie1112** [comment]
@PritKalariya Yes just do the changes and do another PR and all accept if its good

**Comment by PritKalariya** [comment]
Ok sure. Thanks 👍

**Pull request closed without merging**
