### PR TITLE
fixed variable name(Max_curr)

### PR DESCRIPTION
**Pull request by hemanthkotaprolu**
In Kadane's Algorithm Found a typo. issue #177

### CODE REVIEW

**Comment by hemanthkotaprolu** [comment]
I have also added pattern-search-algorithms for strings. Please let me know if i have to change aything.
Thanks

**Review by jeremie1112 — CHANGES_REQUESTED** [review]
Hello can you move the file please? 
You have added this in "Algorithms/Pattern_Searching_Algorithm/C++/Java/improvedNaivePatternSearch.java"

Can you add it in "Algorithms/Pattern_Searching_Algorithm/Java/improvedNaivePatternSearch.java"
please ?

**Comment by hemanthkotaprolu** [comment]
Yeah will do that.

**Comment by hemanthkotaprolu** [comment]
Just check and let me know @jeremie1112 .
Thanks.

**Review by jeremie1112 — APPROVED** [review]

**Comment by jeremie1112** [comment]
Thank you its better

**Pull request merged**
